### POST request to add new merchant
POST http://localhost:4000/merchants
Content-Type: application/json

{
  "merchantName": "Kid",
  "storeName": "Kid Kat",
  "email": "kidkat@gmail.com",
  "address": "Pune, India",
  "registeredDate": "2022-05-01",
  "phoneNumber": "+127850000010"
}

###