### POST request to add new merchant
POST http://localhost:4000/merchants
Content-Type: application/json

{
  "merchantName": "Urvil",
  "storeName": "UrvilFlights",
  "email": "planesofurvil@gmail.com",
  "address": "Maharashtra, India",
  "registeredDate": "2026-05-10",
  "phoneNumber": "+16666460160"
}

###