### POST request to add new merchant
POST http://localhost:4000/merchants
Content-Type: application/json

{
  "merchantName": "Layon",
  "storeName": "LaysLis",
  "email": "layonlays@gmail.com",
  "address": "Lucknow, India",
  "registeredDate": "2018-12-15",
  "phoneNumber": "+13478000010"
}

###