### POST request to add new merchant
POST http://localhost:4000/merchants
Content-Type: application/json

{
  "merchantName": "Ken",
  "storeName": "Ken Crisps",
  "email": "kencrips@gmail.com",
  "address": "Chennai, India",
  "registeredDate": "2024-03-14",
  "phoneNumber": "+144400000010"
}

###